name: olist_env
channels:
  - defaults
dependencies:
  - python=3.13
  - pandas=2.2.3
  - matplotlib=3.10.0
  - seaborn=0.13.2
  - jupyter=1.1.1
  - numpy=2.1.3
  - pip

#   conda env create -f environment.yml
#   conda activate olist_env